// Generated by scripts/build-galleries.py — do not edit by hand.

// images/photography
const photographyImages = [
  "1.jpg",
  "2.jpg",
  "3.jpg",
  "4.jpg",
  "5.jpg",
  "6.jpg",
  "7.jpg",
  "8.jpg",
  "9.jpg",
  "10.jpg",
  "11.jpg",
  "12.jpg",
  "13.jpg",
  "14.jpg",
  "15.jpg",
  "16.jpg",
  "17.jpg",
  "18.jpg",
  "19.jpg",
  "20.jpg",
  "21.jpg",
  "22.jpg",
  "23.jpg",
  "24.jpg",
];

// images/pod
const podImages = [
  "File_000.png",
  "IMG_0142.JPG",
  "IMG_0230.JPG",
  "IMG_0304.JPG",
  "IMG_0366.JPG",
  "IMG_0367.JPG",
  "IMG_0369.JPG",
  "IMG_0370.JPG",
  "IMG_0423.PNG",
  "IMG_0502.JPG",
  "IMG_0503.JPG",
  "IMG_0534.JPG",
  "Untitled_Artwork.png"
];
