// Mobile nav
const toggle = document.querySelector(".nav-toggle");
const nav = document.querySelector(".site-nav");
toggle.addEventListener("click", () => {
  const open = nav.classList.toggle("open");
  toggle.setAttribute("aria-expanded", open);
});
nav.querySelectorAll("a").forEach(a => a.addEventListener("click", () => {
  nav.classList.remove("open");
  toggle.setAttribute("aria-expanded", "false");
}));

// Reveal on scroll
document.querySelectorAll(".section h2").forEach(el => el.classList.add("reveal"));
const io = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) { entry.target.classList.add("visible"); io.unobserve(entry.target); }
  });
}, { threshold: 0.12 });
document.querySelectorAll(".reveal").forEach(el => io.observe(el));

// Active nav link on scroll
const navLinks = nav.querySelectorAll("a[href^='#']");
const sectionObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      navLinks.forEach(l => l.classList.toggle("active", l.getAttribute("href") === `#${entry.target.id}`));
    }
  });
}, { rootMargin: "-50% 0px -50% 0px" });
document.querySelectorAll("main section[id]").forEach(s => sectionObserver.observe(s));

// Contact form — static site, so open the user's mail client.
document.getElementById("contact-form").addEventListener("submit", e => {
  e.preventDefault();
  const data = new FormData(e.target);
  const subject = encodeURIComponent(`${data.get("type")} enquiry from ${data.get("name")}`);
  const body = encodeURIComponent(`${data.get("message")}\n\n— ${data.get("name")} (${data.get("email")})`);
  window.location.href = `mailto:hello@rawkaki.art?subject=${subject}&body=${body}`;
  document.getElementById("form-note").textContent = "Thanks! Your email app should open to send the message.";
  e.target.reset();
});

document.getElementById("year").textContent = new Date().getFullYear();

// Galleries — `photographyImages` and `podImages` come from js/gallery-images.js,
// generated by scripts/build-galleries.py from images/photography and images/pod.

function loadGallery(containerId, folder, files, altPrefix) {
  const container = document.getElementById(containerId);
  if (!container) return;
  const fragment = document.createDocumentFragment();
  files.forEach((file, i) => {
    const figure = document.createElement("figure");
    figure.className = "gallery-item";
    const button = document.createElement("button");
    button.type = "button";
    button.className = "gallery-open";
    const img = document.createElement("img");
    img.src = `${folder}/${file}`;
    img.alt = `${altPrefix} ${i + 1}`;
    img.loading = "lazy";
    img.decoding = "async";
    img.addEventListener("error", () => figure.remove());
    button.setAttribute("aria-label", `Open ${img.alt}`);
    button.addEventListener("click", () => openLightbox(container, img));
    button.appendChild(img);
    figure.appendChild(button);
    fragment.appendChild(figure);
  });
  container.appendChild(fragment);
}

// Lightbox
const lightbox = document.getElementById("lightbox");
const lightboxImg = lightbox.querySelector(".lightbox-img");
let lightboxImages = [];
let lightboxIndex = 0;

function showLightboxImage(index) {
  lightboxIndex = (index + lightboxImages.length) % lightboxImages.length;
  const img = lightboxImages[lightboxIndex];
  lightboxImg.src = img.currentSrc || img.src;
  lightboxImg.alt = img.alt;
}

function openLightbox(container, img) {
  // Query at open time so images removed after a load error are skipped.
  lightboxImages = [...container.querySelectorAll(".gallery-item img")];
  showLightboxImage(lightboxImages.indexOf(img));
  lightbox.showModal();
  document.body.style.overflow = "hidden";
}


lightbox.addEventListener("close", () => { document.body.style.overflow = ""; });
lightbox.querySelector(".lightbox-close").addEventListener("click", () => lightbox.close());
lightbox.querySelector(".lightbox-prev").addEventListener("click", () => showLightboxImage(lightboxIndex - 1));
lightbox.querySelector(".lightbox-next").addEventListener("click", () => showLightboxImage(lightboxIndex + 1));
lightbox.addEventListener("click", e => { if (e.target === lightbox) lightbox.close(); });
lightbox.addEventListener("keydown", e => {
  if (e.key === "ArrowLeft") showLightboxImage(lightboxIndex - 1);
  if (e.key === "ArrowRight") showLightboxImage(lightboxIndex + 1);
});

function shuffle(items) {
  const a = [...items];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

loadGallery("pod-gallery", "images/pod", shuffle(typeof podImages !== "undefined" ? podImages : []), "Rawkaki print-on-demand design");

loadGallery("photography-gallery", "images/photography", shuffle(typeof photographyImages !== "undefined" ? photographyImages : []), "Rawkaki photography");